services:
  gateway:
    build:
      context: .
      dockerfile: gateway/Dockerfile
    ports:
      - "8080:8080"
    environment:
      BACKEND_URL: http://backend:8081
    depends_on:
      - backend
    networks:
      - cache-net

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "8081:8081"
    networks:
      - cache-net
  
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "4200:4200"
    depends_on:
      - gateway
    networks:
      - cache-net

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - cache-net
  
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - gateway
      - backend
    networks:
      - cache-net

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    networks:
      - cache-net


networks:
  cache-net:
    name: cache-net
    driver: bridge