services:
  gateway:
    build:
      context: .
      dockerfile: gateway/Dockerfile
    ports:
      - "8080:8080"
    environment:
      BACKEND_URL: http://backend:8081
    depends_on:
      - backend
    networks:
      - cache-net

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    networks:
      - cache-net

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - cache-net


networks:
  cache-net:
    name: cache-net
    driver: bridge